version: '3.9'
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    command: "/bin/bash"
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    expose:
      - 3000
    volumes:
        - .:/app
    environment:
        APP_ENV: "development"
        PORT: 3000
