apiVersion: v1
kind: ConfigMap
metadata:
  name: restapiconfig
data:
  PORT: "3000"
  LOG_LEVEL: "info"
  APP_ENV: "production"
  HERE_API_KEY: "-ZgDQiB9BtkuI_pYPTuXDKIEtTX-qjZyPmZJEyVE-Zs"
  HERE_API_URL: "https://geocode.search.hereapi.com"
  HERE_API_ROUTES_URL: "https://router.hereapi.com/v8/routes"
  HERE_API_VERSION: "v1"
  CIUDAD: "CABA"
